"""Download 17lands public draft data to data/raw/ (idempotent, resumable).

URL pattern (verified 2026-07):
https://17lands-public.s3.amazonaws.com/analysis_data/draft_data/draft_data_public.<SET>.<EVENT>.csv.gz
"""

import argparse
import sys
from pathlib import Path

import requests

URL_TEMPLATE = (
    "https://17lands-public.s3.amazonaws.com/analysis_data/{kind}_data/"
    "{kind}_data_public.{set_code}.{event}.csv.gz"
)

# Candidate codes probed by --probe-all. Unknown/absent codes simply 403/404 and are
# reported unavailable; extend freely — probing is a cheap HEAD request.
CANDIDATE_SETS = [
    "STX", "AFR", "MID", "VOW", "NEO", "SNC", "HBG", "DMU", "BRO", "ONE",
    "SIR", "MOM", "MAT", "LTR", "WOE", "LCI", "KTK", "RVR", "MKM", "OTJ",
    "MH3", "BLB", "DSK", "FDN", "PIO", "DFT", "TDM", "FIN", "EOE", "SPM",
    "TLA", "ECL", "MSH",
]
EVENTS = ["PremierDraft", "TradDraft"]

RAW_DIR = Path("data/raw")


def url_for(set_code: str, event: str, kind: str = "draft") -> str:
    return URL_TEMPLATE.format(set_code=set_code, event=event, kind=kind)


def probe(set_code: str, event: str, session: requests.Session | None = None,
          kind: str = "draft") -> int | None:
    """Return Content-Length if the file exists on S3, else None."""
    sess = session or requests
    resp = sess.head(url_for(set_code, event, kind), timeout=30)
    if resp.status_code == 200:
        return int(resp.headers.get("Content-Length", 0))
    return None


def dest_path(set_code: str, event: str, dest_dir: Path = RAW_DIR,
              kind: str = "draft") -> Path:
    return dest_dir / f"{kind}_data_public.{set_code}.{event}.csv.gz"


def download(set_code: str, event: str, dest_dir: Path = RAW_DIR,
             kind: str = "draft") -> Path:
    """Idempotent, resumable download via HTTP Range onto a .part file."""
    dest_dir.mkdir(parents=True, exist_ok=True)
    final = dest_path(set_code, event, dest_dir, kind)
    remote_size = probe(set_code, event, kind=kind)
    if remote_size is None:
        raise FileNotFoundError(f"No S3 object for {set_code} {event}")
    if final.exists() and final.stat().st_size == remote_size:
        print(f"{final.name}: already complete ({remote_size:,} bytes)")
        return final

    part = final.with_suffix(final.suffix + ".part")
    start = part.stat().st_size if part.exists() else 0
    headers = {"Range": f"bytes={start}-"} if start else {}
    mode = "ab" if start else "wb"
    with requests.get(url_for(set_code, event, kind), headers=headers, stream=True, timeout=60) as r:
        if start and r.status_code != 206:  # server ignored Range; restart clean
            start, mode = 0, "wb"
        r.raise_for_status()
        with open(part, mode) as f:
            for chunk in r.iter_content(chunk_size=1 << 20):
                f.write(chunk)
    if part.stat().st_size != remote_size:
        raise IOError(f"{part}: got {part.stat().st_size:,} bytes, expected {remote_size:,}")
    part.rename(final)
    print(f"{final.name}: downloaded ({remote_size:,} bytes)")
    return final


def probe_all(out_md: Path = Path("docs/data_cards/available.md")) -> None:
    session = requests.Session()
    rows = []
    for set_code in CANDIDATE_SETS:
        sizes = {event: probe(set_code, event, session) for event in EVENTS}
        rows.append((set_code, sizes))
        avail = ", ".join(e for e, s in sizes.items() if s) or "—"
        print(f"{set_code}: {avail}")
    out_md.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# 17lands S3 draft-data availability",
        "",
        "Generated by `draftbot fetch --probe-all`. Sizes are gzipped bytes.",
        "",
        "| Set | PremierDraft | TradDraft |",
        "|-----|--------------|-----------|",
    ]
    for set_code, sizes in rows:
        cells = [f"{sizes[e]:,}" if sizes[e] else "—" for e in EVENTS]
        lines.append(f"| {set_code} | {cells[0]} | {cells[1]} |")
    n_avail = sum(1 for _, s in rows if s["PremierDraft"])
    lines += ["", f"{n_avail} sets with PremierDraft data."]
    out_md.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_md} ({n_avail} sets with PremierDraft)")


def main(argv=None):
    parser = argparse.ArgumentParser(prog="draftbot fetch")
    parser.add_argument("--set", dest="set_code")
    parser.add_argument("--event", default="PremierDraft", choices=EVENTS)
    parser.add_argument("--probe-all", action="store_true")
    parser.add_argument("--dest", type=Path, default=RAW_DIR)
    args = parser.parse_args(argv)
    if args.probe_all:
        probe_all()
        return 0
    if not args.set_code:
        parser.error("--set required unless --probe-all")
    download(args.set_code, args.event, args.dest)
    return 0


if __name__ == "__main__":
    sys.exit(main())
